"""
Provides top-level imports
"""

from trendify import base
from trendify import formats
from trendify import plotting
from trendify import store
from trendify import styling

from trendify.base import (
    DataProduct,
    HashableBase,
    Pen,
    ProductGenerator,
    ProductList,
    ProductType,
    R,
    Tag,
    Tags,
    data_product,
    helpers,
    pen,
)
from trendify.formats import (
    AxisScale,
    Format2D,
    PlottableData2D,
    TableEntry,
    XYData,
    format2d,
    table,
)
from trendify.plotting import (
    AxLine,
    HistogramEntry,
    HistogramStyle,
    LineOrientation,
    PlotlyFigure,
    Point2D,
    SingleAxisFigure,
    Trace2D,
    axline,
    figure,
    histogram,
    point,
    trace,
)
from trendify.store import (
    ProductStore,
    SCHEMA_VERSION,
    connect,
    db,
    decode_tag,
    encode_tag,
    product_store,
    tags,
)
from trendify.styling import (
    Grid,
    GridAxis,
    GridTheme,
    Legend,
    LegendLocation,
    Marker,
    grid,
    legend,
    marker,
)

__all__ = [
    "SCHEMA_VERSION",
    "AxLine",
    "AxisScale",
    "DataProduct",
    "Format2D",
    "Grid",
    "GridAxis",
    "GridTheme",
    "HashableBase",
    "HistogramEntry",
    "HistogramStyle",
    "Legend",
    "LegendLocation",
    "LineOrientation",
    "Marker",
    "Pen",
    "PlotlyFigure",
    "PlottableData2D",
    "Point2D",
    "ProductGenerator",
    "ProductList",
    "ProductStore",
    "ProductType",
    "R",
    "SingleAxisFigure",
    "TableEntry",
    "Tag",
    "Tags",
    "Trace2D",
    "XYData",
    "axline",
    "base",
    "connect",
    "data_product",
    "db",
    "decode_tag",
    "encode_tag",
    "figure",
    "format2d",
    "formats",
    "grid",
    "helpers",
    "histogram",
    "legend",
    "marker",
    "pen",
    "plotting",
    "point",
    "product_store",
    "store",
    "styling",
    "table",
    "tags",
    "trace",
]
